[workspace]
resolver = "2"

members = [
    "c2pa_c",
    "cawg_identity",
    "cli",
    "export_schema",
    "internal/crypto",
    "internal/status-tracker",
    "make_test_images",
    "sdk",
]

[workspace.package]
version = "0.49.3"

[profile.release]
strip = true  # Automatically strip symbols from the binary. 
opt-level = 3
lto = "thin"  # Link time optimization.
