[workspace]
resolver = "3"

members = [
    "c2pa_c_ffi",
    "c2pa_cbor",
    "cli",
    "export_schema",
    "macros",
    "make_test_images",
    "sdk",
]

# members in this workspace can share this version setting
[workspace.package]
version = "0.76.0"

[workspace.dependencies]
c2pa = { path = "sdk", default-features = false }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = 3
lto = "thin"  # Link time optimization.
