[workspace]
resolver = "3"

members = [
    "c2pa_c_ffi",
    "cli",
    "export_schema",
    "macros",
    "make_test_images",
    "sdk",
]

# members in this workspace can share this version setting
[workspace.package]
version = "0.75.4"

[workspace.dependencies]
c2pa = { path = "sdk", default-features = false }

# Remove once http://github.com/chipsenkbeil/typed-path/pull/57 is merged and released
[patch.crates-io]
typed-path = { git = "https://github.com/cdmurph32/typed-path", branch = "wasip2_fix" }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = 3
lto = "thin"  # Link time optimization.
