name: Update schemas in contentauth/json-manifest-reference
on:
  push:
    tags:
      - "c2pa-v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch to contentauth/opensource.contentauth.org
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: c2pa-rs-release
          repository: contentauth/opensource.contentauth.org
          token: ${{ secrets.TRIGGER_JSON_MANIFEST_UPDATE }}
